"""
Old Textbooks Review App
=========================
A web interface for reviewing and approving/skipping items flagged
by the stacks analyzer. Reads from the latest analysis spreadsheet
and saves your decisions to a JSON file.

HOW TO RUN:
    python review_app.py

Then open your browser to: http://localhost:5000

Decisions are saved automatically as you click buttons.
When done, use the Export button to download a CSV of all decisions.

Files used:
    output/latest_analysis.xlsx  -- generated by analyze.py
    output/decisions.json        -- your approve/skip decisions (auto-saved)
"""

import io
from datetime import datetime
from pathlib import Path

import pandas as pd
from flask import Flask, jsonify, render_template, request, send_file

BASE_DIR      = Path(__file__).parent
OUTPUT_DIR    = BASE_DIR / "output"
ANALYSIS_FILE = OUTPUT_DIR / "latest_analysis.xlsx"
DECISIONS_FILE = OUTPUT_DIR / "decisions.json"

OUTPUT_DIR.mkdir(exist_ok=True)

app = Flask(__name__)

# ============================================================================
# DATA HELPERS
# ============================================================================

def load_analysis():
    """Load the analysis Excel file. Returns a DataFrame or None."""
    if not ANALYSIS_FILE.exists():
        return None
    df = pd.read_excel(ANALYSIS_FILE, dtype=str).fillna("")
    return df


def load_decisions():
    """Load saved decisions from JSON. Returns a dict keyed by MMS_ID."""
    import json
    if not DECISIONS_FILE.exists():
        return {}
    with open(DECISIONS_FILE) as f:
        return json.load(f)


def save_decisions(decisions):
    """Persist decisions dict to JSON."""
    import json
    with open(DECISIONS_FILE, "w") as f:
        json.dump(decisions, f, indent=2)

# ============================================================================
# ROUTES
# ============================================================================

@app.route("/")
def index():
    """Main review page."""
    if not ANALYSIS_FILE.exists():
        return (
            "<h2 style='font-family:sans-serif;padding:2rem'>No analysis file found.</h2>"
            "<p style='font-family:sans-serif;padding:0 2rem'>"
            "Run <code>python analyze.py</code> first, then come back here.</p>"
        ), 404
    return render_template("review.html")


@app.route("/api/items")
def get_items():
    """
    Return items as JSON with optional filtering.

    Query params:
        confidence  -- OBVIOUS | LIKELY | UNCLEAR | all
        action      -- MOVE | REVIEW | all
        location    -- STACK | OVERSIZE | all
        decision    -- pending | approved | skipped | all
        search      -- text search against title, author, call number
    """
    df = load_analysis()
    if df is None:
        return jsonify({"error": "No analysis file found"}), 404

    decisions = load_decisions()

    confidence_filter = request.args.get("confidence", "all")
    action_filter     = request.args.get("action",     "all")
    location_filter   = request.args.get("location",   "all")
    decision_filter   = request.args.get("decision",   "all")
    search            = request.args.get("search",     "").strip().lower()

    filtered = df.copy()

    if confidence_filter != "all":
        filtered = filtered[filtered["Confidence"] == confidence_filter]

    if action_filter != "all":
        filtered = filtered[
            filtered["Recommended_Action"].str.contains(action_filter, case=False, na=False)
        ]

    if location_filter != "all":
        filtered = filtered[filtered["Location"] == location_filter]

    if search:
        mask = (
            filtered["Title"].str.lower().str.contains(search, na=False)
            | filtered["Author"].str.lower().str.contains(search, na=False)
            | filtered["Call_Number"].str.lower().str.contains(search, na=False)
        )
        filtered = filtered[mask]

    # Decision filter
    if decision_filter == "pending":
        filtered = filtered[~filtered["MMS_ID"].isin(decisions)]
    elif decision_filter == "approved":
        approved = {k for k, v in decisions.items() if v.get("decision") == "APPROVE"}
        filtered = filtered[filtered["MMS_ID"].isin(approved)]
    elif decision_filter == "skipped":
        skipped = {k for k, v in decisions.items() if v.get("decision") == "SKIP"}
        filtered = filtered[filtered["MMS_ID"].isin(skipped)]

    # Build response, adding current decision info to each row
    items = []
    for _, row in filtered.iterrows():
        item = row.to_dict()
        mms_id = item.get("MMS_ID", "")
        dec = decisions.get(mms_id, {})
        item["_decision"]      = dec.get("decision", "")
        item["_decision_notes"] = dec.get("notes", "")
        item["_decision_time"] = dec.get("timestamp", "")
        items.append(item)

    return jsonify({"items": items, "total": len(items)})


@app.route("/api/stats")
def get_stats():
    """Return summary counts for the stats bar."""
    df = load_analysis()
    if df is None:
        return jsonify({"error": "No analysis file found"}), 404

    decisions = load_decisions()
    approved  = sum(1 for v in decisions.values() if v.get("decision") == "APPROVE")
    skipped   = sum(1 for v in decisions.values() if v.get("decision") == "SKIP")

    return jsonify({
        "total":    len(df),
        "obvious":  int((df["Confidence"] == "OBVIOUS").sum()),
        "likely":   int((df["Confidence"] == "LIKELY").sum()),
        "unclear":  int((df["Confidence"] == "UNCLEAR").sum()),
        "approved": approved,
        "skipped":  skipped,
        "pending":  len(df) - len(decisions),
    })


@app.route("/api/decide", methods=["POST"])
def decide():
    """
    Save or clear a decision for one item.

    JSON body:
        mms_id   -- the item's MMS ID
        decision -- "APPROVE" | "SKIP" | "CLEAR"
        notes    -- optional text note
    """
    data     = request.get_json()
    mms_id   = data.get("mms_id", "").strip()
    decision = data.get("decision", "")
    notes    = data.get("notes", "")

    if not mms_id or decision not in ("APPROVE", "SKIP", "CLEAR"):
        return jsonify({"error": "Invalid request"}), 400

    decisions = load_decisions()

    if decision == "CLEAR":
        decisions.pop(mms_id, None)
    else:
        decisions[mms_id] = {
            "decision":  decision,
            "notes":     notes,
            "timestamp": datetime.now().isoformat(),
        }

    save_decisions(decisions)
    return jsonify({"ok": True, "total_decisions": len(decisions)})


@app.route("/export")
def export_decisions():
    """Download all items with their decisions as a CSV."""
    df = load_analysis()
    if df is None:
        return "No analysis file found", 404

    decisions = load_decisions()

    df["Decision"] = df["MMS_ID"].map(
        lambda mid: decisions.get(mid, {}).get("decision", "PENDING")
    )
    df["Decision_Notes"] = df["MMS_ID"].map(
        lambda mid: decisions.get(mid, {}).get("notes", "")
    )

    export_cols = [
        "MMS_ID", "Title", "Author", "Call_Number", "Location",
        "Edition", "Confidence", "Confidence_Score", "Confidence_Reasons",
        "Recommended_Action", "Decision", "Decision_Notes",
    ]
    export_cols = [c for c in export_cols if c in df.columns]

    buf = io.BytesIO()
    df[export_cols].to_csv(buf, index=False)
    buf.seek(0)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    return send_file(
        buf,
        mimetype="text/csv",
        as_attachment=True,
        download_name=f"old_textbooks_decisions_{timestamp}.csv",
    )


# ============================================================================
# MAIN
# ============================================================================

if __name__ == "__main__":
    print("=" * 55)
    print("OLD TEXTBOOKS REVIEW APP")
    print("=" * 55)
    print(f"Analysis file:  {ANALYSIS_FILE}")
    print(f"Decisions file: {DECISIONS_FILE}")
    print()
    print("Open your browser to:  http://localhost:5001")
    print("Press Ctrl+C to stop.")
    print("=" * 55)
    app.run(debug=False, port=5001)
